---
title: "Gov 50 Final Project"
author: "Soleei Guasp"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to educational policy data in schools across the United States. I want to explore some of the correlations and connections between student test scores, unionization and  student performance through various parts of the country. I am very interested in data concerning the differences in gpd per capital and human capitol amoungst states with district with stronger unions and school committee boards and how it affects the probability of student success and contributions back to their home city. 

## Milestone 

Does the implementation of standardized testing really enhance their human capital? In this study, I plan to examine the extent to which schools who utilize standardized testing and the most test prep has affected the students ability to pursue higher education and a greater life outcome. I hypothesize that there will actually be little to no difference in human capital based on standardized testing that a student might have gone through. People often misconceptualized the significance of standardized testing in believing that this will motivate students more pursue higher education when in reality it might diminish their motivation. I would like to explore this across various socioeconomic district schools if possible as well. I believe it makes no difference because students can choose to pursue other paths such as trade school and still contribute equally to how students who pursue higher education will. This is with the assumption that students who take more standardized tests are more likely to pursue higher education. My sample is composed of 2022-2012 student progress datasets from the National Center of Education Statistics. My unit of analysis is standardized testing rates. The explanatory variables of interest are whether they implemented standardized testing mandatory for graduation (1 = TRUE, 0 = FALSE)  and how often they implemented them (numerical value). My outcome variable would be salaries in the following 10 years (measured in hundred thousands so for example 110k = 11.0). If I observe that there is no greater difference between the salaries of students who did not undergo standardized testing more often than those who did, this would provide sufficient evidence for my hypothesis. If on the other hand, I notice a significant difference in salary, this would prove my hypothesis wrong. I plan to take into consideration the socioeconomic status of each district, since this is a huge confounding variable that can affect my results (or maybe not).

##Milestone 3
```{r}
library(tidyverse)
library(dplyr)

hlo_database <- read_excel("hlo_database.xlsx")

outcome <- hlo_database |>
  group_by(country, year) |>
  summarize(mean_HLO = mean(hlo)) %>% 
  ungroup()

outcome <- outcome %>% 
  left_join(hlo_database, by = c("country", "year"))

ggplot(data = outcome,
       group = incomegroup,
       mapping = aes(x = year,
                     y = mean_HLO,
                     color = country,
                     fill = country)) +
  geom_point()
  
outcome %>% 
  ggplot(aes(x = year, y = mean_HLO, fill = region, color = region)) + geom_point() + facet_wrap(~ incomegroup)

```